package com.ujjwal.bankease.enums;

public enum AuditAction {LOGIN_SUCCESS, LOGIN_FAILED, REGISTER, TRANSFER, BILL_PAYMENT, LOAN_APPLICATION, LOAN_DECISION, INVESTMENT_PURCHASE, INVESTMENT_REDEEM, ACCOUNT_STATUS_CHANGE}